SUPABASE_URL = "https://duhsskisgksyozjdrusl.supabase.co"
SUPABASE_KEY = "sb_publishable_ChRLE6JchVDz1lW6ExRCDA_ibizrTGU"

[admins]
"1" = "49bd2aab5ca8c640d9461d138268eaba3a12831bd634ce9e65c013425460de1b"

[admin_nombres]
"1" = "Admin"
